# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weather.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rweather.proto\"/\n\x08Location\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\"8\n\x0e\x46orecastPeriod\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x18\n\x10\x64\x65tailedForecast\x18\x02 \x01(\t\"4\n\x10\x46orecastResponse\x12 \n\x07periods\x18\x01 \x03(\x0b\x32\x0f.ForecastPeriod2=\n\x0eWeatherService\x12+\n\x0bGetForecast\x12\t.Location\x1a\x11.ForecastResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'weather_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOCATION']._serialized_start=17
  _globals['_LOCATION']._serialized_end=64
  _globals['_FORECASTPERIOD']._serialized_start=66
  _globals['_FORECASTPERIOD']._serialized_end=122
  _globals['_FORECASTRESPONSE']._serialized_start=124
  _globals['_FORECASTRESPONSE']._serialized_end=176
  _globals['_WEATHERSERVICE']._serialized_start=178
  _globals['_WEATHERSERVICE']._serialized_end=239
# @@protoc_insertion_point(module_scope)
